return function(t)
  local config = require("md-viewer.config")
  config.reset()
  local cfg = config.setup({ split = { width = 0.4 }, image = { backend = "cells" } })
  t.eq(0.4, cfg.split.width, "configuration override")
  t.eq(45, cfg.split.min_width, "configuration deep merge")
  t.eq(false, cfg.security.network, "network default")
  t.eq(true, cfg.preview.pinned, "preview remains pinned by default")
  t.eq(true, cfg.preview.loading, "graphical preview loading indicator default")
  t.eq(80, cfg.preview.loading_interval_ms, "loading indicator animation interval")
  t.eq(true, cfg.sync.mouse_scroll, "preview mouse scrolling default")
  t.eq(true, cfg.render.scroll_past_end, "preview scrolls past its last block")
  t.eq(true, cfg.render.fast_scroll, "fast scroll capture default")
  t.eq(nil, cfg.render.fast_scroll_fps, "scroll captures have no artificial FPS cap")
  t.eq(16, cfg.render.font_size_px, "preview base font size default")
  config.reset()
  local bad_font_ok, bad_font_err = pcall(config.setup, { render = { font_size_px = 0 } })
  t.eq(false, bad_font_ok, "non-positive render.font_size_px is rejected")
  t.ok(tostring(bad_font_err):match("font_size_px"), "invalid font_size_px error names the offending option")
  config.reset()
  local sized_cfg = config.setup({ render = { font_size_px = 20 } })
  t.eq(20, sized_cfg.render.font_size_px, "render.font_size_px is overridable")
  config.reset()
  config.setup({ split = { width = 0.4 }, image = { backend = "cells" } })
  t.eq(nil, cfg.image.raw_zindex, "raw z-index defers to the terminal profile default until overridden")
  t.eq(nil, cfg.image.double_buffer, "double buffering defers to the terminal profile default until overridden")
  t.eq(1, cfg.image.raw_statusline_guard_cells, "raw graphics reserve a statusline boundary cell")
  t.eq(1, cfg.image.raw_overlay_bleed_cells, "passive overlay cutouts bleed one trailing column by default")
  t.eq(0, cfg.image.raw_cell_offset_px.x, "no sub-cell placement offset until the terminal is calibrated")
  t.eq(0, cfg.image.raw_cell_offset_px.y, "no sub-cell placement offset until the terminal is calibrated")
  t.eq(50, cfg.image.ui_poll_ms, "raw previews poll for no-autocmd floating UI")
  config.reset()
  local bleed_ok, bleed_err = pcall(config.setup, { image = { raw_overlay_bleed_cells = -1 } })
  t.eq(false, bleed_ok, "a negative overlay bleed is rejected")
  t.ok(tostring(bleed_err):match("raw_overlay_bleed_cells"), "the bleed error names the offending option")
  config.reset()
  local offset_ok, offset_err = pcall(config.setup, { image = { raw_cell_offset_px = { x = -4, y = 0 } } })
  t.eq(false, offset_ok, "a negative sub-cell offset is rejected")
  t.ok(tostring(offset_err):match("raw_cell_offset_px"), "the offset error names the offending option")
  config.reset()
  local calibrated = config.setup({ image = { raw_cell_offset_px = { x = 10, y = 0 } } })
  t.eq(10, calibrated.image.raw_cell_offset_px.x, "a measured sub-cell offset is accepted")
  t.eq("auto", cfg.terminal.profile, "terminal profile defaults to auto")
  t.eq("auto", cfg.terminal.kitty_graphics, "kitty graphics inference defaults to auto")
  t.eq("off", cfg.terminal.probe, "active graphics probe is off by default")
end
