return function(t)
  local config = require("md-viewer.config")
  config.reset()
  local cfg = config.setup({ split = { width = 0.4 }, image = { backend = "cells" } })
  t.eq(0.4, cfg.split.width, "configuration override")
  t.eq(45, cfg.split.min_width, "configuration deep merge")
  t.eq(false, cfg.security.network, "network default")
  t.eq(true, cfg.preview.pinned, "preview remains pinned by default")
  t.eq(true, cfg.preview.loading, "graphical preview loading indicator default")
  t.eq(80, cfg.preview.loading_interval_ms, "loading indicator animation interval")
  t.eq(true, cfg.sync.mouse_scroll, "preview mouse scrolling default")
  t.eq(true, cfg.render.scroll_past_end, "preview scrolls past its last block")
  t.eq(true, cfg.render.fast_scroll, "fast scroll capture default")
  t.eq(nil, cfg.render.fast_scroll_fps, "scroll captures have no artificial FPS cap")
  t.eq(nil, cfg.image.raw_zindex, "raw z-index defers to the terminal profile default until overridden")
  t.eq(nil, cfg.image.double_buffer, "double buffering defers to the terminal profile default until overridden")
  t.eq(1, cfg.image.raw_statusline_guard_cells, "raw graphics reserve a statusline boundary cell")
  t.eq(50, cfg.image.ui_poll_ms, "raw previews poll for no-autocmd floating UI")
  t.eq("auto", cfg.terminal.profile, "terminal profile defaults to auto")
  t.eq("auto", cfg.terminal.kitty_graphics, "kitty graphics inference defaults to auto")
  t.eq("off", cfg.terminal.probe, "active graphics probe is off by default")
end
