// The stream splicer: does a token become exactly the bytes it stands in for?
//
// This is the de-risk for the whole client-render design, and it runs with no
// terminal, no browser and no network. The claim being proven is narrow and
// total: a frame transmitted as a token and spliced back produces a byte stream
// **identical** to the one the plugin sends today. If that holds, every
// terminal that works today keeps working, because nothing reaching it changed.
//
// `tests/fixtures/splice-upload.esc` is the pinned answer, and
// `tests/lua/cases/backend_kitty.lua` asserts the Lua `chunks()` against the
// same file from the same generated input. Two implementations in two languages
// checked against one artifact: neither can drift without a failure here or
// there.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createSplicer, frameToken, kittyChunks } from "../../renderer/src/splice.js";
import { createFrameStore } from "../../renderer/src/frames.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const GOLDEN = fs.readFileSync(path.resolve(here, "../fixtures/splice-upload.esc"));
const CONTROL = "a=t,f=100,t=d,q=2,i=42";

// Generated rather than checked in, and generated by the same three rules in
// tests/lua/cases/backend_kitty.lua: a real PNG header (so the Lua backend's
// `png_dimensions` accepts it) followed by 3076 bytes of `i % 251`. The prime
// keeps the pattern from aligning with base64's three-byte grouping, and 3100
// bytes is deliberately just over the 3072 that fills one 4096-character
// transmission chunk -- so the golden exercises the `m=1` continuation and the
// bare `q=2` control every chunk after the first carries.
function fixturePng() {
  const head = Buffer.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
    0, 0, 0, 13,
    0x49, 0x48, 0x44, 0x52,
    0, 0, 0x03, 0xde, // width 990
    0, 0, 0x03, 0xfc, // height 1020
  ]);
  const filler = Buffer.alloc(3076);
  for (let index = 0; index < filler.length; index += 1) filler[index] = index % 251;
  return Buffer.concat([head, filler]);
}

const PNG = fixturePng();

function splicerFor(bytes = PNG) {
  const frames = createFrameStore();
  const events = [];
  const ref = frames.put(bytes);
  return { frames, ref, events, splicer: createSplicer({ frames, onEvent: (e) => events.push(e) }) };
}

function through(splicer, buffer, sliceAt) {
  const out = [];
  for (const piece of sliceAt) out.push(splicer.push(piece));
  out.push(splicer.flush());
  assert.equal(Buffer.concat(out).length >= 0, true);
  return Buffer.concat(out);
}

test("chunks() is byte-identical to the pinned golden", () => {
  assert.equal(PNG.length, 3100);
  const upload = Buffer.from(kittyChunks(PNG.toString("base64"), CONTROL), "latin1");
  assert.deepEqual(upload, GOLDEN);
});

test("the golden has the shape the Kitty protocol requires", () => {
  // Asserted from the protocol rather than from the implementation, so a shared
  // mistake in both ports still fails something.
  const commands = GOLDEN.toString("latin1").split("\x1b_G").slice(1);
  assert.equal(commands.length, 2, "3100 bytes is 4136 base64 characters: one full chunk and a remainder");
  assert.equal(commands[0].startsWith(`${CONTROL},m=1;`), true, "the first chunk carries the caller's control and m=1");
  assert.equal(commands[1].startsWith("q=2,m=0;"), true, "later chunks carry q=2 alone, and the last says m=0");
  for (const command of commands) assert.equal(command.endsWith("\x1b\\"), true, "every command is ST-terminated");
  const payloads = commands.map((c) => c.slice(c.indexOf(";") + 1, -2));
  assert.equal(payloads[0].length, 4096, "chunks are 4096 characters of base64");
  assert.equal(payloads.join(""), PNG.toString("base64"), "the payloads reassemble to exactly the frame");
});

test("a token becomes exactly the upload it stands in for", () => {
  const { splicer, ref } = splicerFor();
  const out = splicer.push(Buffer.from(frameToken(ref, CONTROL), "latin1"));
  assert.deepEqual(out, GOLDEN);
  assert.deepEqual(splicer.flush(), Buffer.alloc(0));
  assert.equal(splicer.stats().spliced, 1);
});

test("a token spliced mid-stream leaves everything around it untouched", () => {
  const { splicer, ref } = splicerFor();
  const before = Buffer.from("\x1b[s\x1b[5;3H", "latin1");
  const after = Buffer.from("\x1b_Ga=p,q=2,C=1,i=42,p=7,x=0,y=0,w=10,h=10,c=2,r=2,z=-3;\x1b\\\x1b[u", "latin1");
  const stream = Buffer.concat([before, Buffer.from(frameToken(ref, CONTROL), "latin1"), after]);
  const out = Buffer.concat([splicer.push(stream), splicer.flush()]);
  assert.deepEqual(out, Buffer.concat([before, GOLDEN, after]));
});

test("a token split across every possible read boundary still splices", () => {
  // The one failure mode a byte-stream filter has: reads land wherever the
  // kernel puts them, and a token straddling two of them must not be half
  // recognized. Every split point of a real token is checked, including inside
  // the ESC _ marker and inside the magic.
  const token = Buffer.from(frameToken("aabbccdd-1", CONTROL), "latin1");
  const stream = Buffer.concat([Buffer.from("head"), token, Buffer.from("tail")]);
  const expected = Buffer.concat([Buffer.from("head"), GOLDEN, Buffer.from("tail")]);
  for (let split = 1; split < stream.length; split += 1) {
    const frames = createFrameStore();
    const ref = frames.put(PNG);
    assert.equal(ref.length > 0, true);
    // The store mints its own reference, so drive the splicer with a store that
    // answers the fixed one this stream names.
    const splicer = createSplicer({ frames: { get: (name) => (name === "aabbccdd-1" ? PNG : null) } });
    const out = through(splicer, stream, [stream.subarray(0, split), stream.subarray(split)]);
    assert.deepEqual(out, expected, `split at byte ${split}`);
  }
});

test("a token delivered one byte at a time still splices", () => {
  const splicer = createSplicer({ frames: { get: () => PNG } });
  const stream = Buffer.from(frameToken("x1", CONTROL), "latin1");
  const pieces = [];
  for (let index = 0; index < stream.length; index += 1) pieces.push(stream.subarray(index, index + 1));
  assert.deepEqual(through(splicer, stream, pieces), GOLDEN);
});

test("a passing Kitty upload is forwarded verbatim and is not held", () => {
  // The common case, and the one where buffering would cost real latency: a
  // 300KB `a=t` from a session that is not client-rendering at all.
  const { splicer } = splicerFor();
  const upload = GOLDEN;
  const first = splicer.push(upload.subarray(0, 100));
  assert.deepEqual(first, upload.subarray(0, 100), "nothing is held back waiting for this sequence to terminate");
  const rest = splicer.push(upload.subarray(100));
  assert.deepEqual(Buffer.concat([first, rest, splicer.flush()]), upload);
  assert.equal(splicer.stats().tokens, 0);
});

test("an unknown reference is forwarded rather than swallowed", () => {
  // Either it is our token and the frame is gone -- in which case the terminal
  // discards an APC string it does not recognize and this frame does not appear
  // -- or it was never ours, in which case eating it would have destroyed
  // somebody's output.
  const { splicer, events } = splicerFor();
  const token = Buffer.from(frameToken("nosuchframe", CONTROL), "latin1");
  assert.deepEqual(Buffer.concat([splicer.push(token), splicer.flush()]), token);
  assert.equal(splicer.stats().unknown, 1);
  assert.deepEqual(events, [{ kind: "unknown-frame", ref: "nosuchframe" }]);
});

test("a malformed token is forwarded rather than interpreted", () => {
  const { splicer, ref } = splicerFor();
  for (const body of ["tx", "tx;a;b;c", `tx;${ref};a=t;bad`, "rm;-rf;/", `tx;bad ref;${CONTROL}`, `tx;${ref};a=t;`]) {
    const bytes = Buffer.from(`\x1b_MDV1;${body}\x1b\\`, "latin1");
    assert.deepEqual(Buffer.concat([splicer.push(bytes), splicer.flush()]), bytes, body);
  }
  assert.equal(splicer.stats().spliced, 0);
});

test("an unterminated token is released rather than buffered forever", () => {
  const splicer = createSplicer({ frames: { get: () => PNG } });
  const junk = Buffer.concat([Buffer.from("\x1b_MDV1;tx;abc;", "latin1"), Buffer.alloc(2048, 0x41)]);
  const out = Buffer.concat([splicer.push(junk), splicer.flush()]);
  assert.deepEqual(out, junk);
  assert.equal(splicer.stats().malformed, 1);
});

test("a partial token at end of stream is released by flush", () => {
  const splicer = createSplicer({ frames: { get: () => PNG } });
  const partial = Buffer.from("\x1b_MDV1;tx;abc", "latin1");
  assert.deepEqual(splicer.push(partial), Buffer.alloc(0), "held while it could still complete");
  assert.deepEqual(splicer.flush(), partial, "released when it cannot");
});

test("a lone ESC at end of stream is released by flush", () => {
  const splicer = createSplicer({ frames: { get: () => PNG } });
  assert.deepEqual(splicer.push(Buffer.from("ok\x1b", "latin1")), Buffer.from("ok"));
  assert.deepEqual(splicer.flush(), Buffer.from("\x1b", "latin1"));
});

test("two tokens back to back both splice", () => {
  const splicer = createSplicer({ frames: { get: () => PNG } });
  const stream = Buffer.from(frameToken("a", CONTROL) + frameToken("b", CONTROL), "latin1");
  assert.deepEqual(Buffer.concat([splicer.push(stream), splicer.flush()]), Buffer.concat([GOLDEN, GOLDEN]));
});

test("a splicer that fails latches into passthrough instead of losing the session", () => {
  const splicer = createSplicer({
    frames: { get() { throw new Error("store exploded"); } },
  });
  const token = Buffer.from(frameToken("a", CONTROL), "latin1");
  assert.deepEqual(splicer.push(token), token, "what was held is released with the chunk that broke it");
  assert.equal(splicer.stats().panicked, "store exploded");
  const later = Buffer.from("ordinary output\n");
  assert.deepEqual(splicer.push(later), later, "and everything after it passes through untouched");
});

test("a single-chunk frame produces one command with m=0", () => {
  // The other end of the size range: a 24-byte PNG header is 32 base64
  // characters, which is one chunk that is also the last.
  const tiny = PNG.subarray(0, 24);
  const splicer = createSplicer({ frames: { get: () => tiny } });
  const out = Buffer.concat([splicer.push(Buffer.from(frameToken("t", CONTROL), "latin1")), splicer.flush()]);
  assert.equal(out.toString("latin1"), `\x1b_G${CONTROL},m=0;${tiny.toString("base64")}\x1b\\`);
});

test("the frame store bounds itself and keeps what is being used", () => {
  const frames = createFrameStore({ maxFrames: 3 });
  const first = frames.put(Buffer.from("one"));
  frames.put(Buffer.from("two"));
  frames.put(Buffer.from("three"));
  // Reading `first` makes it the newest, so the next insert must evict "two".
  assert.deepEqual(frames.get(first), Buffer.from("one"));
  frames.put(Buffer.from("four"));
  assert.deepEqual(frames.get(first), Buffer.from("one"), "a frame that keeps being read keeps being held");
  assert.equal(frames.stats().frames, 3);
  assert.equal(frames.stats().evicted, 1);
});

test("frame references are usable inside an escape sequence", () => {
  const frames = createFrameStore();
  for (let index = 0; index < 5; index += 1) {
    assert.match(frames.put(Buffer.from([index])), /^[A-Za-z0-9_-]{1,64}$/);
  }
  // Two stores are two processes as far as a reference is concerned: a Lua side
  // holding one from before a companion restart must not be answered by the
  // one that replaced it.
  const other = createFrameStore();
  assert.notEqual(frames.put(Buffer.from("x")), other.put(Buffer.from("x")));
});

test("a byte-for-byte scan of the whole stream finds no other MDV1 sequence", () => {
  // The stream this filter sits in front of carries arbitrary program output.
  // A false positive would eat somebody's bytes, so the guard is that the
  // marker cannot occur inside a Kitty upload: base64 has no ESC in it, and an
  // APC string contains no ESC before its terminator.
  assert.equal(GOLDEN.includes(Buffer.from("\x1b_MDV1", "latin1")), false);
  assert.equal(PNG.toString("base64").includes("\x1b"), false);
});
